# Generated by Django 5.2.8 on 2026-02-14 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('BusStopCode', models.IntegerField(primary_key=True, serialize=False)),
                ('BusStopName', models.CharField(max_length=200)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('TrainStationCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('TrainStationName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('BusDetailCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('BusNumber', models.IntegerField()),
                ('BusStopCode', models.ForeignKey(db_column='BusStopCode', on_delete=django.db.models.deletion.CASCADE, to='LearnItGlobal.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopAmenity',
            fields=[
                ('BusStopAmenityCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('Amenity', models.CharField(choices=[('Convenience Store', 'Convenience Store'), ('Wheelchair', 'Wheelchair'), ('Toilet', 'Toilet'), ('ATM', 'Atm')], max_length=50)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('AmenityLocationDescription', models.CharField(default='No Further Information', max_length=100)),
                ('BusStopCode', models.ForeignKey(db_column='BusStopCode', on_delete=django.db.models.deletion.CASCADE, to='LearnItGlobal.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='TrainDetail',
            fields=[
                ('TrainDetailCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('Direction', models.BooleanField(default=False)),
                ('Time', models.TimeField()),
                ('Line', models.CharField(choices=[('East-West', 'Ew'), ('North-South', 'Ns'), ('North-East', 'Ne'), ('Circle', 'Ccl'), ('Thompson-East Coast', 'Tel'), ('Bukit Panjang LRT', 'Bplrt'), ('Downtown', 'Dt'), ('Sengkang LRT', 'Sklrt'), ('Punggol LRT', 'Pglrt')], max_length=50)),
                ('TrainStationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnItGlobal.trainstation')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStationAmenity',
            fields=[
                ('TrainStationAmenityCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('Amenity', models.CharField(choices=[('Convenience Store', 'Convenience Store'), ('Wheelchair', 'Wheelchair'), ('Toilet', 'Toilet'), ('ATM', 'Atm')], max_length=50)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('AmenityLocationDescription', models.CharField(default='No Further Information', max_length=100)),
                ('TrainStationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnItGlobal.trainstation')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStationExit',
            fields=[
                ('TrainStationExitCode', models.BigAutoField(primary_key=True, serialize=False)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ExitDescription', models.CharField(max_length=200)),
                ('ExitDigit', models.CharField(max_length=1)),
                ('TrainStationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnItGlobal.trainstation')),
            ],
        ),
    ]
