# Generated by Django 5.2.8 on 2026-02-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnItGlobal', '0001_initial'),
    ]

    operations = [
    ]
