# Generated by Django 5.2.8 on 2026-02-16 04:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnItGlobal', '0002_auto_20260208_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstopamenity',
            name='AmenityLocationDescription',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='trainstationamenity',
            name='AmenityLocationDescription',
            field=models.TextField(null=True, blank=True),
        ),
    ]

