# Generated by Django 5.2.8 on 2026-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnItGlobal', '0003_auto_20260208_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstopamenity',
            name='AmenityName',
            field=models.CharField(default='POSB ATM', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainstationamenity',
            name='AmenityName',
            field=models.CharField(default='POSB ATM', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busstopamenity',
            name='AmenityLocationDescription',
            field=models.CharField(default='No Further Information', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainstationamenity',
            name='AmenityLocationDescription',
            field=models.CharField(default='No Further Information', max_length=100),
        ),
    ]
