# Generated by Django 5.2.8 on 2026-02-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnItGlobal', '0004_busstopamenity_amenityname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traindetail',
            name='Direction',
        ),
        migrations.RemoveField(
            model_name='traindetail',
            name='Time',
        ),
        migrations.AddField(
            model_name='traindetail',
            name='TrainStationLineNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
