# Generated by Django 5.2.8 on 2026-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnItGlobal', '0005_remove_traindetail_direction_remove_traindetail_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstation',
            name='LineCode',
            field=models.CharField(default='NE1', max_length=10),
            preserve_default=False,
        ),
    ]
